-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 14:32:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aktualnosci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aktualnosci` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aktualnosci` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(60) CHARACTER SET 'utf8mb3' NOT NULL,
  `opis` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`nauczyciele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nauczyciele` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nauczyciele` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` INT NOT NULL,
  `nazwisko` INT NOT NULL,
  `kod` VARCHAR(8) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`uczniowie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`uczniowie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`uczniowie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `nazwisko` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `adres` VARCHAR(90) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(40) CHARACTER SET 'utf8mb3' NOT NULL,
  `numer_telefonu` CHAR(9) CHARACTER SET 'utf8mb3' NOT NULL,
  `kod` VARCHAR(8) CHARACTER SET 'utf8mb3' NOT NULL,
  `haslo` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `klasa` VARCHAR(8) CHARACTER SET 'utf8mb3' NOT NULL,
  `plan_lekcji_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`oceny`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oceny` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oceny` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ocena` VARCHAR(2) CHARACTER SET 'utf8mb3' NOT NULL,
  `opis` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `data` DATE NOT NULL,
  `przedmiot` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `uczniowie_id` INT UNSIGNED NOT NULL,
  `nauczyciele_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oceny_uczniowie_idx` (`uczniowie_id` ASC) VISIBLE,
  INDEX `fk_oceny_nauczyciele1_idx` (`nauczyciele_id` ASC) VISIBLE,
  CONSTRAINT `fk_oceny_uczniowie`
    FOREIGN KEY (`uczniowie_id`)
    REFERENCES `mydb`.`uczniowie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oceny_nauczyciele1`
    FOREIGN KEY (`nauczyciele_id`)
    REFERENCES `mydb`.`nauczyciele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`plan_lekcji`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plan_lekcji` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plan_lekcji` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa_przedmiotu` VARCHAR(11) CHARACTER SET 'utf8mb3' NOT NULL,
  `dzien` VARCHAR(15) CHARACTER SET 'utf8mb3' NOT NULL,
  `godzina` VARCHAR(2) CHARACTER SET 'utf8mb3' NOT NULL,
  `kod_nauczyciela` VARCHAR(8) CHARACTER SET 'utf8mb3' NOT NULL,
  `klasa` VARCHAR(5) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`uwagi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`uwagi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`uwagi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(50) NOT NULL DEFAULT 'Tytuł',
  `opis` VARCHAR(300) CHARACTER SET 'utf8mb3' NOT NULL,
  `pozytywna` TINYINT(1) NOT NULL,
  `data` DATE NULL,
  `uczniowie_id` INT UNSIGNED NOT NULL,
  `nauczyciele_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_uwagi_uczniowie1_idx` (`uczniowie_id` ASC) VISIBLE,
  INDEX `fk_uwagi_nauczyciele1_idx` (`nauczyciele_id` ASC) VISIBLE,
  CONSTRAINT `fk_uwagi_uczniowie1`
    FOREIGN KEY (`uczniowie_id`)
    REFERENCES `mydb`.`uczniowie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uwagi_nauczyciele1`
    FOREIGN KEY (`nauczyciele_id`)
    REFERENCES `mydb`.`nauczyciele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`wiadomosci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wiadomosci` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wiadomosci` (
  `id` INT UNSIGNED NOT NULL,
  `tytul` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `tresc` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `kod_autora` VARCHAR(8) CHARACTER SET 'utf8mb3' NOT NULL,
  `kod_adresata` VARCHAR(8) CHARACTER SET 'utf8mb3' NOT NULL,
  `odczytana` TINYINT(1) NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`kody`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kody` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kody` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kod` VARCHAR(8) NULL,
  `uczen` TINYINT NULL,
  `id_wlasciciela` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
